### ISSUE TITLE
fix: resolve pre-existing gateway-api TS2742 typecheck failure (excluded from typescript-critical gate)

### ISSUE THREAD

**Issue by wiredchaos** [AGENTROPOLIS-CITY-OF-AGENTS/AGENTROPOLIS-PAYRAIL#13]
## Summary

`apps/gateway-api` fails TypeScript typecheck with a pre-existing `TS2742` error, byte-identical to `main` (not a regression from PR #12).

```
src/index.ts(4,7): error TS2742: The inferred type of 'app' cannot be named without a reference to
'.pnpm/@types+express-serve-static-core@4.19.9/.../@types/express-serve-static-core'.
This is likely not portable. A type annotation is necessary.
```

## Context

- `app` is `express()` and its inferred HTTP type is not portable → TS requires an explicit type annotation.
- Root cause: the `express` `Request`/`Response` body type isn't resolved by `@types/express` at the declaration site, so the inferred `app` type carries a non-portable reference.
- Confirmed byte-identical to `main` by VERITY (PR #12 delta). Not introduced by the hardening work.
- PR #12 explicitly scopes the `typescript-critical` GitHub gate to the critical PAYRAIL financial packages; `apps/gateway-api` is excluded from that gate (it is a consumer app, not one of the financial core packages).

## Fix options to evaluate

1. Add an explicit type annotation to `app`, e.g. type the express app, and import the correct `@types/express-serve-static-core` `Express` type:
   `import express, { Express } from "express";` then `const app: Express = express();`
2. Ensure `@types/express-serve-static-core` is resolved at the package level so the inferred type is portable.

## Acceptance

- `pnpm --filter @agentropolis/gateway-api typecheck` exits 0.
- No change to monetary / authority / replay / settlement / receipt / SignedIntent / redaction / RPC semantics.
- Registry: follow-up to re-include `apps/gateway-api` in the `typescript-critical` gate once fixed.
